### ISSUE TITLE
 nvmedit nvm2json fails with "TypeError: Cannot read property 'lwr' of undefined"

### ISSUE THREAD

**Issue by cdhawan** [AlCalzone/node-zwave-js#4205]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
npx @zwave-js/nvmedit nvm2json --in .\NVM_2022-02-08.bin --out nvm.json

What do you observe?
TypeError: Cannot read property 'lwr' of undefined
    at nvmObjectsToJSON (C:\Users\cdhaw\AppData\Roaming\npm-cache\_npx\20300\node_modules\@zwave-js\nvmedit\build\convert.js:149:35)
    at nvmToJSON (C:\Users\cdhaw\AppData\Roaming\npm-cache\_npx\20300\node_modules\@zwave-js\nvmedit\build\convert.js:552:17)
    at Object.handler (C:\Users\cdhaw\AppData\Roaming\npm-cache\_npx\20300\node_modules\@zwave-js\nvmedit\build\cli.js:41:40)

What did you expect to happen?
Successful execution of this command. 

### Device information

Manufacturer: Zooz
Model name: ZST10-700
Node ID in your network: 1

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
nvmedit : 8.11.4
zwavejs2mqtt: 6.5.0
zwave-js: 8.11.2

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

TypeError: Cannot read property 'lwr' of undefined
    at nvmObjectsToJSON (C:\Users\cdhaw\AppData\Roaming\npm-cache\_npx\20300\node_modules\@zwave-js\nvmedit\build\convert.js:149:35)
    at nvmToJSON (C:\Users\cdhaw\AppData\Roaming\npm-cache\_npx\20300\node_modules\@zwave-js\nvmedit\build\convert.js:552:17)
    at Object.handler (C:\Users\cdhaw\AppData\Roaming\npm-cache\_npx\20300\node_modules\@zwave-js\nvmedit\build\cli.js:41:40)

**Comment by AlCalzone** [comment]
Interesting... Can you send me the `.bin` file so I can check it out? Either post here or via e-mail.

**Comment by cdhawan** [comment]
> Interesting... Can you send me the `.bin` file so I can check it out? Either post here or via e-mail.

Thank you AlCalzone for the taking of this. I sent you .bin via e-mail.
