### ISSUE TITLE
Controller becomes unresponsive when trying to remove dead node

### ISSUE THREAD

**Issue by kendrome** [AlCalzone/node-zwave-js#4611]
I have one node that is dead that I'm unable to remove. When attempt to remove it, the controller locks up and becomes unresponsive for a at least a few minutes, sometimes longer. If I wait a while then usually the controller will start working again on it's own. I think this leads to side affects like half my node's statuses being unknown in Home Assistant after updating zwavejs2mqtt until I ping all them.
 
 
 Here is what I see in the debug logs:
```
2022-05-10 14:17:43.000 INFO ZWAVE: Calling api removeFailedNode with args: [ 37, [length]: 1 ]
2022-05-10T19:17:43.003Z CNTRLR » [Node 037] pinging the node...
2022-05-10T19:18:48.029Z CNTRLR [Node 037] ping failed: Timeout while waiting for a callback from the controll
er (ZW0200)
2022-05-10T19:18:49.037Z CNTRLR Failed to execute controller command after 1/3 attempts. Scheduling next try i
n 100 ms.
2022-05-10T19:18:50.143Z CNTRLR Failed to execute controller command after 2/3 attempts. Scheduling next try i
n 1100 ms.
2022-05-10T19:18:53.249Z CNTRLR Failed to execute controller command after 1/3 attempts. Scheduling next try i
n 100 ms.
2022-05-10T19:18:54.352Z CNTRLR Failed to execute controller command after 2/3 attempts. Scheduling next try i
n 1100 ms.
2022-05-10T19:18:56.456Z CNTRLR [Node 006] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
2022-05-10T19:18:57.962Z CNTRLR Failed to execute controller command after 1/3 attempts. Scheduling next try i
n 100 ms.
2022-05-10T19:18:59.069Z CNTRLR Failed to execute controller command after 2/3 attempts. Scheduling next try i
n 1100 ms.
2022-05-10T19:19:01.178Z CNTRLR [Node 006] did not respond after 2/3 attempts. Scheduling next try in 500 ms.
2022-05-10T19:19:02.684Z CNTRLR Failed to execute controller command after 1/3 attempts. Scheduling next try i
n 100 ms.
2022-05-10T19:19:03.785Z CNTRLR Failed to execute controller command after 2/3 attempts. Scheduling next try i
n 1100 ms.
2022-05-10 14:19:05.893 ERROR ZWAVE-SERVER: Timeout while waiting for an ACK from the controller (ZW0200)
ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:3449:23)
at Driver.sendCommand (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:3623:28)
at MultilevelSwitchCCAPI.get (/opt/node_modules/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts:114:22)
at MultilevelSwitchCCAPI.<computed> (/opt/node_modules/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts:417:24)
at ZWaveNode.pollValue (/opt/node_modules/zwave-js/src/lib/node/Node.ts:1017:15)
at Function.handle (/opt/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:51:36)
at Object.node (/opt/node_modules/@zwave-js/server/dist/lib/server.js:40:91)
at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:96:99)
at WebSocket.<anonymous> (/opt/node_modules/@zwave-js/server/dist/lib/server.js:49:45)
at WebSocket.emit (node:events:526:28)
2022-05-10T19:19:06.908Z CNTRLR Failed to execute controller command after 1/3 attempts. Scheduling next try i
n 100 ms.
2022-05-10T19:19:08.012Z CNTRLR Failed to execute controller command after 2/3 attempts. Scheduling next try i
n 1100 ms.
2022-05-10 14:19:10.119 INFO ZWAVE: Timeout while waiting for an ACK from the controller (ZW0200) removeFailedNode undefined
2022-05-10T19:19:11.134Z CNTRLR Failed to execute controller command after 1/3 attempts. Scheduling next try i
n 100 ms.
2022-05-10T19:19:12.237Z CNTRLR Failed to execute controller command after 2/3 attempts. Scheduling next try i
n 1100 ms.
2022-05-10T19:19:14.340Z CNTRLR [Node 020] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
2022-05-10T19:19:15.847Z CNTRLR Failed to execute controller command after 1/3 attempts. Scheduling next try i
n 100 ms.
2022-05-10T19:19:16.951Z CNTRLR Failed to execute controller command after 2/3 attempts. Scheduling next try i
n 1100 ms.
```

**Comment by AlCalzone** [comment]
Please make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` or `silly` and attach it here as a file.

**Comment by kendrome** [comment]
Thanks, here you go. If it helps finding where the log starts, it's Node 37 I'm attempting to remove
[zwavejs_2022-05-11.log](https://github.com/zwave-js/node-zwave-js/files/8671856/zwavejs_2022-05-11.log)

**Comment by AlCalzone** [comment]
Okay, that's one I haven't seen before. The entire stick becomes unresponsive when trying to ping the node during the startup procedure. When you attempt to remove it, it is already too late. Unfortunately, there's no way to disable the pinging, since it determines the node status. Manually editing the controller memory is out of the question since your stick firmware is too old.

If you have access to a Windows PC, you can try to remove the node using Silabs' PC controller (part of Simplicity Studio).
