### ISSUE TITLE
Multiple nodes become dead during getAvailableFirmware checks

### ISSUE THREAD

**Issue by jcam** [AlCalzone/node-zwave-js#5069]
I've noticed that almost daily, a few or up to dozens of nodes will become dead and need to be 'pinged' to come back online.

From the log, it appears to be related to the getAvailableFirmware checks:
2022-09-14 00:02:28.676 INFO ZWAVE: Node 62 is now dead
2022-09-14 00:02:28.703 ERROR ZWAVE-SERVER: Failed to send the command after 1 attempts (Status Fail) (ZW0202)
ZWaveError: Failed to send the command after 1 attempts (Status Fail) (ZW0202)
    at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:3895:23)
    at Driver.sendCommandInternal (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4086:28)
    at Driver.sendCommand (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4201:15)
    at Proxy.get (/opt/node_modules/@zwave-js/cc/src/cc/ManufacturerSpecificCC.ts:106:24)
    at ZWaveController.getAvailableFirmwareUpdates (/opt/node_modules/zwave-js/src/lib/controller/Controller.ts:4523:5)
    at Function.handle (/opt/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:203:54)
    at Object.controller (/opt/node_modules/@zwave-js/server/dist/lib/server.js:38:103)
    at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:96:99)
    at WebSocket.<anonymous> (/opt/node_modules/@zwave-js/server/dist/lib/server.js:49:45)
    at WebSocket.emit (node:events:527:28)

[zwavejs2mqtt-logs-firmware-check-fail.zip](https://github.com/zwave-js/node-zwave-js/files/9562611/zwavejs2mqtt-logs-firmware-check-fail.zip)

**Comment by AlCalzone** [comment]
Your stick is still on a broken firmware version (firmware version:    7.16). Update to at least 7.17.2
