### ISSUE TITLE
Inovelli NZW30 does not seem to produce double/triple tap events similar to the LZW31-SN

### ISSUE THREAD

**Issue by snicker** [AlCalzone/node-zwave-js#5203]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

I am guessing that the configuration for this device is not set up to respond to double and triple tap notifications:
https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0312/nzw30.json

What do you observe?

No central scene notifications are logged when the switch is double/triple tapped

What did you expect to happen?

Central scene events should be generated by this device

according to Inovelli, these switches should generate up to 5x taps.

https://support.inovelli.com/portal/en/kb/articles/faq-s-button-mapping-for-scene-control#NZW30-S_-_Gen_1_OnOff_Switch

### Device information

Manufacturer: Inovelli
Model name: NZW30
Node ID in your network: 6

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 0.1.74

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### If yes, where did it work?

This device did have double tap support under openzwave

### Attach Driver Logfile

```
2022-11-12T16:36:02.160Z CNTRLR « [Node 006] ping successful
2022-11-12T16:36:02.235Z CNTRLR   [Node 007] The node is alive.
2022-11-12T16:36:02.238Z CNTRLR   [Node 007] The node is ready to be used
2022-11-12T16:36:02.257Z CNTRLR « [Node 007] ping successful
2022-11-12T16:36:03.634Z CNTRLR   [Node 011] The node is alive.
2022-11-12T16:36:03.635Z CNTRLR   [Node 011] The node is ready to be used
2022-11-12T16:36:03.641Z CNTRLR « [Node 011] ping successful
2022-11-12T16:36:03.734Z CNTRLR   [Node 012] The node is alive.
2022-11-12T16:36:03.735Z CNTRLR   [Node 012] The node is ready to be used
2022-11-12T16:36:03.741Z CNTRLR « [Node 012] ping successful
2022-11-12T16:36:12.385Z CNTRLR   [Node 014] The node did not respond after 1 attempts, it is presumed dead
2022-11-12T16:36:12.387Z CNTRLR   [Node 014] The node is dead.
2022-11-12T16:36:12.405Z CNTRLR   [Node 014] ping failed: Failed to send the command after 1 attempts (Status No
                                  Ack) (ZW0204)
2022-11-12T16:36:12.489Z CNTRLR   [Node 016] The node is alive.
2022-11-12T16:36:12.490Z CNTRLR   [Node 016] The node is ready to be used
2022-11-12T16:36:12.494Z CNTRLR « [Node 016] ping successful
2022-11-12T16:36:12.533Z CNTRLR   [Node 017] The node is alive.
2022-11-12T16:36:12.534Z CNTRLR   [Node 017] The node is ready to be used
2022-11-12T16:36:12.539Z CNTRLR « [Node 017] ping successful
2022-11-12T16:36:12.574Z CNTRLR   [Node 018] The node is alive.
2022-11-12T16:36:12.574Z CNTRLR   [Node 018] The node is ready to be used
2022-11-12T16:36:12.580Z CNTRLR « [Node 018] ping successful
2022-11-12T16:36:12.680Z CNTRLR   [Node 024] The node is alive.
2022-11-12T16:36:12.681Z CNTRLR   [Node 024] The node is ready to be used
2022-11-12T16:36:12.685Z CNTRLR « [Node 024] ping successful
2022-11-12T16:36:12.735Z CNTRLR   [Node 025] The node is alive.
2022-11-12T16:36:12.741Z CNTRLR   [Node 025] The node is ready to be used
2022-11-12T16:36:12.748Z CNTRLR « [Node 025] ping successful
2022-11-12T16:36:12.897Z CNTRLR   [Node 026] The node is alive.
2022-11-12T16:36:12.898Z CNTRLR   [Node 026] The node is ready to be used
2022-11-12T16:36:12.905Z CNTRLR « [Node 026] ping successful
2022-11-12T16:36:12.944Z CNTRLR   [Node 027] The node is alive.
2022-11-12T16:36:12.945Z CNTRLR   [Node 027] The node is ready to be used
2022-11-12T16:36:12.952Z CNTRLR « [Node 027] ping successful
2022-11-12T16:36:12.991Z CNTRLR   [Node 028] The node is alive.
2022-11-12T16:36:12.993Z CNTRLR   [Node 028] The node is ready to be used
2022-11-12T16:36:12.999Z CNTRLR « [Node 028] ping successful
2022-11-12T16:36:13.095Z CNTRLR   [Node 033] The node is alive.
2022-11-12T16:36:13.096Z CNTRLR   [Node 033] The node is ready to be used
2022-11-12T16:36:13.107Z CNTRLR « [Node 033] ping successful
2022-11-12T16:36:13.187Z CNTRLR   [Node 034] The node is alive.
2022-11-12T16:36:13.205Z CNTRLR   [Node 034] The node is ready to be used
2022-11-12T16:36:13.212Z CNTRLR « [Node 034] ping successful
2022-11-12T16:36:13.318Z CNTRLR   [Node 036] The node is alive.
2022-11-12T16:36:13.320Z CNTRLR   [Node 036] The node is ready to be used
2022-11-12T16:36:13.328Z CNTRLR « [Node 036] ping successful
2022-11-12T16:36:13.435Z CNTRLR   [Node 038] The node is alive.
2022-11-12T16:36:13.436Z CNTRLR   [Node 038] The node is ready to be used
2022-11-12T16:36:13.441Z CNTRLR « [Node 038] ping successful
2022-11-12T16:36:13.512Z CNTRLR   [Node 046] The node is alive.
2022-11-12T16:36:13.513Z CNTRLR   [Node 046] The node is ready to be used
2022-11-12T16:36:13.519Z CNTRLR « [Node 046] ping successful
2022-11-12T16:36:13.558Z CNTRLR   [Node 047] The node is alive.
2022-11-12T16:36:13.559Z CNTRLR   [Node 047] The node is ready to be used
2022-11-12T16:36:13.566Z CNTRLR « [Node 047] ping successful
2022-11-12T16:36:17.673Z CNTRLR   [Node 048] The node did not respond after 1 attempts, it is presumed dead
2022-11-12T16:36:17.674Z CNTRLR   [Node 048] The node is dead.
2022-11-12T16:36:17.711Z CNTRLR   [Node 048] ping failed: Failed to send the command after 1 attempts (Status No
                                  Ack) (ZW0204)
2022-11-12T16:36:17.751Z CNTRLR   [Node 049] The node is alive.
2022-11-12T16:36:17.759Z CNTRLR   [Node 049] The node is ready to be used
2022-11-12T16:36:17.764Z CNTRLR « [Node 049] ping successful
2022-11-12T16:36:17.832Z CNTRLR   [Node 051] The node is alive.
2022-11-12T16:36:17.833Z CNTRLR   [Node 051] The node is ready to be used
2022-11-12T16:36:17.839Z CNTRLR « [Node 051] ping successful
2022-11-12T16:36:17.936Z CNTRLR   [Node 052] The node is alive.
2022-11-12T16:36:17.937Z CNTRLR   [Node 052] The node is ready to be used
2022-11-12T16:36:17.946Z CNTRLR « [Node 052] ping successful
2022-11-12T16:36:19.380Z CNTRLR   [Node 053] The node is alive.
2022-11-12T16:36:19.381Z CNTRLR   [Node 053] The node is ready to be used
2022-11-12T16:36:19.390Z CNTRLR « [Node 053] ping successful
2022-11-12T16:36:19.618Z CNTRLR   [Node 054] The node is alive.
2022-11-12T16:36:19.619Z CNTRLR   [Node 054] The node is ready to be used
2022-11-12T16:36:19.623Z CNTRLR « [Node 054] ping successful
2022-11-12T16:36:19.686Z CNTRLR   [Node 055] The node is alive.
2022-11-12T16:36:19.687Z CNTRLR   [Node 055] The node is ready to be used
2022-11-12T16:36:19.688Z CNTRLR   All nodes are ready to be used
2022-11-12T16:36:19.691Z CNTRLR « [Node 055] ping successful
2022-11-12T16:36:30.466Z CNTRLR   [Node 015] treating BasicCC::Set as a report
New client
2022-11-12T16:36:49.855Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2022-11-12T16:37:09.185Z CNTRLR   [Node 024] Timed out while waiting for a response from the node (ZW0201)
Z-Wave error ZWaveError: Cannot check for firmware updates for node 24: Failed to query firmware version from the node! (ZW0260)
    at ZWaveController.getAvailableFirmwareUpdates (/usr/src/node_modules/zwave-js/src/lib/controller/Controller.ts:4535:10)
    at Function.handle (/usr/src/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:204:30)
    at Client.receiveMessage (/usr/src/node_modules/@zwave-js/server/dist/lib/server.js:105:62) {
  code: 260,
  context: undefined,
  transactionSource: undefined
}
2022-11-12T16:39:28.377Z CNTRLR   [Node 015] treating BasicCC::Set as a report
2022-11-12T16:40:51.126Z CNTRLR « [Node 020] received wakeup notification
2022-11-12T16:40:51.130Z CNTRLR   [Node 020] The node is now awake.
2022-11-12T16:40:52.288Z CNTRLR » [Node 020] Sending node back to sleep...
2022-11-12T16:40:52.347Z CNTRLR   [Node 020] The node is now asleep.
2022-11-12T16:41:12.140Z CNTRLR   [Node 015] treating BasicCC::Set as a report
2022-11-12T16:41:42.556Z CNTRLR « [Node 024] Received updated node info
2022-11-12T16:44:10.084Z CNTRLR   [Node 015] treating BasicCC::Set as a report
```

**Comment by snicker** [comment]
I'm running zwavejs in a homeassistant addon container- I'm not sure how to access a log file to download. I can get a shell on the container but I'm also not sure where the log file is located in the filesystem. can provide if that information is readily available. These docs don't seem to indicate where to find it either

https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index

**Comment by kpine** [comment]
> I am guessing that the configuration for this device is not set up to respond to double and triple tap notifications:

Device config files aren't used for scenes, the device reports that it supports them. A config file setting is only required for Basic Set events, but that doesn't look to apply here.

> I'm running zwavejs in a homeassistant addon container- I'm not sure how to access a log file to download.

HA-related topics are in HA docs: https://www.home-assistant.io/integrations/zwave_js/, and for logs specifically: https://www.home-assistant.io/integrations/zwave_js/#how-to-access-the-z-wave-logs.

There is no log file for the official add-on. You can capture logs as indicated above, and click the download button for the file, or copy and paste the text into a file, and attach here. You should be using Debug log level and capturing the logs when you are trying to use the device.

**Comment by snicker** [comment]
Well, after further research I think I'm going to close this ticket. It does appear that earlier versions of the NZW30 do not have scene support :

https://support.inovelli.com/portal/en/kb/articles/what-s-the-difference-between-red-and-black-series
