### ISSUE TITLE
 Z-WAVE-SERVER: Cannot send this message because it would exceed the maximum payload length! (ZW0215) 

### ISSUE THREAD

**Issue by thecobra666** [AlCalzone/node-zwave-js#5660]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Call a scene to set a light to a color and brightness level, when the light is already on.

What do you observe?
Says error ZW0215. 

What did you expect to happen?
The light to change color.

Set a scene in HA, call it = ok
Call another scene = nok error.
Turn off the light
turn it immediately back on
Call the scene = ok

### Device information

Manufacturer: Qubino
Model name:  ZMNKAD1
Node ID in your network: 60
Device ID 345-82-8 (0x0159-0x0008-0x0052) 

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

zwave-js-ui: 8.13.1.33a6f57
zwave-js: 10.14.0
home id: 3439378454
home hex: 0xcd00c016

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

50/50 of the times this works, so rather doesn't work unless turning off the light.

### Attach Driver Logfile

```
18:37:03.275 SERIAL « 0x010e0004000b0631050422095dd4006a (16 bytes)
18:37:03.278 SERIAL » [ACK] (0x06)
18:37:03.281 CNTRLR [Node 011] [Multilevel Sensor] Power: metadata updated [Endpoint 0]
18:37:03.284 CNTRLR [Node 011] [~] [Multilevel Sensor] Power: 202.9 => 239.7 [Endpoint 0]
18:37:03.286 DRIVER « [Node 011] [REQ] [ApplicationCommand]
└─[MultilevelSensorCCReport]
type: Power
scale: Watt
value: 239.7
18:37:07.275 SERIAL « 0x010e0004000b063105042207c5d400fc (16 bytes)
18:37:07.278 SERIAL » [ACK] (0x06)
18:37:07.281 CNTRLR [Node 011] [Multilevel Sensor] Power: metadata updated [Endpoint 0]
18:37:07.284 CNTRLR [Node 011] [~] [Multilevel Sensor] Power: 239.7 => 198.9 [Endpoint 0]
18:37:07.286 DRIVER « [Node 011] [REQ] [ApplicationCommand]
└─[MultilevelSensorCCReport]
type: Power
scale: Watt
value: 198.9
18:37:12.275 SERIAL « 0x010e0004000b063105042209abd4009c (16 bytes)
18:37:12.280 SERIAL » [ACK] (0x06)
18:37:12.289 CNTRLR [Node 011] [Multilevel Sensor] Power: metadata updated [Endpoint 0]
18:37:12.294 CNTRLR [Node 011] [~] [Multilevel Sensor] Power: 198.9 => 247.5 [Endpoint 0]
18:37:12.298 DRIVER « [Node 011] [REQ] [ApplicationCommand]
└─[MultilevelSensorCCReport]
type: Power
scale: Watt
value: 247.5
18:37:17.275 SERIAL « 0x010e0004000b06310504220827d40011 (16 bytes)
18:37:17.277 SERIAL » [ACK] (0x06)
18:37:17.280 CNTRLR [Node 011] [Multilevel Sensor] Power: metadata updated [Endpoint 0]
18:37:17.284 CNTRLR [Node 011] [~] [Multilevel Sensor] Power: 247.5 => 208.7 [Endpoint 0]
18:37:17.286 DRIVER « [Node 011] [REQ] [ApplicationCommand]
└─[MultilevelSensorCCReport]
type: Power
scale: Watt
value: 208.7
18:37:22.311 SERIAL » 0x010a00133c039f01c62513b7 (12 bytes)
18:37:22.313 DRIVER » [Node 060] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 19
└─[Security2CCNonceGet]
sequence number: 198
18:37:22.317 SERIAL « [ACK] (0x06)
18:37:22.320 SERIAL « 0x0104011301e8 (6 bytes)
18:37:22.322 SERIAL » [ACK] (0x06)
18:37:22.324 DRIVER « [RES] [SendData]
was sent: true
18:37:22.381 SERIAL « 0x011800131300000701cd7f7f7f7f0101030c0000000201000020 (26 bytes)
18:37:22.383 SERIAL » [ACK] (0x06)
18:37:22.385 DRIVER « [REQ] [SendData]
callback id: 19
transmit status: OK, took 70 ms
repeater node IDs: 12
routing attempts: 1
protocol & route speed: Z-Wave, 40 kbit/s
ACK RSSI: -51 dBm
ACK RSSI on repeaters: N/A
ACK channel no.: 1
TX channel no.: 1
18:37:22.463 SERIAL « 0x011c0004003c149f020001338e4445f5e9ade3757693e7a4297a0dcd00fd (30 bytes)
18:37:22.465 SERIAL » [ACK] (0x06)
18:37:22.467 DRIVER « [Node 060] [REQ] [ApplicationCommand]
└─[Security2CCNonceReport]
sequence number: 0
SOS: true
MOS: false
receiver entropy: 0x338e4445f5e9ade3757693e7a4297a0d
2023-04-13 18:37:22.483 ERROR Z-WAVE-SERVER: Cannot send this message because it would exceed the maximum payload length! (ZW0215)
ZWaveError: Cannot send this message because it would exceed the maximum payload length! (ZW0215)
at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4182:23)
at Driver.sendCommandInternal (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4375:28)
at Driver.sendSupervisedCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4420:27)
at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4477:30)
at ColorSwitchCCAPI.set (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ColorSwitchCC.ts:232:38)
at Proxy.ColorSwitchCCAPI.<computed> (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ColorSwitchCC.ts:461:17)
at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:961:29)
at NodeMessageHandler.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:23:38)
at Object.node (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:41:96)
at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:106:99)
18:37:28.866 SERIAL » 0x0103003bc7 (5 bytes)
18:37:28.869 DRIVER » [REQ] [GetBackgroundRSSI]
18:37:28.874 SERIAL « [ACK] (0x06)
18:37:28.878 SERIAL « 0x0105013bb5aedb (7 bytes)
18:37:28.885 SERIAL » [ACK] (0x06)
18:37:28.889 DRIVER « [RES] [GetBackgroundRSSI]
channel 0: -75 dBm
channel 1: -82 dBm
18:37:36.508 SERIAL » 0x012500133c1e9f03c800e3ba6453bc2ccfa2dcdca85024239f377a0d8bb94deb2 (39 bytes)
e651cd025142e
18:37:36.514 DRIVER » [Node 060] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 20
└─[Security2CCMessageEncapsulation]
│ sequence number: 200
└─[MultiChannelCCCommandEncapsulation]
│ source: 0
│ destination: 1
└─[SupervisionCCGet]
│ session id: 59
│ request updates: true
└─[ColorSwitchCCSet]
Red: 255
Green: 255
Blue: 0
duration: default
18:37:36.518 SERIAL « [ACK] (0x06)
18:37:36.522 SERIAL « 0x0104011301e8 (6 bytes)
18:37:36.528 SERIAL » [ACK] (0x06)
18:37:36.531 DRIVER « [RES] [SendData]
was sent: true
18:37:36.594 SERIAL « 0x011800131400000801c97f7f7f7f0101030c000000020100002c (26 bytes)
18:37:36.596 SERIAL » [ACK] (0x06)
18:37:36.600 DRIVER « [REQ] [SendData]
callback id: 20
transmit status: OK, took 80 ms
repeater node IDs: 12
routing attempts: 1
protocol & route speed: Z-Wave, 40 kbit/s
ACK RSSI: -55 dBm
ACK RSSI on repeaters: N/A
ACK channel no.: 1
TX channel no.: 1
18:37:36.684 SERIAL « 0x011c0004003c149f020101d4ab991d0eeceb432f64d8feaa825176cd004c (30 bytes)
18:37:36.686 SERIAL » [ACK] (0x06)
18:37:36.690 DRIVER « [Node 060] [REQ] [ApplicationCommand]
└─[Security2CCNonceReport]
sequence number: 1
SOS: true
MOS: false
receiver entropy: 0xd4ab991d0eeceb432f64d8feaa825176
18:37:36.699 CNTRLR [Node 060] failed to decode the message, retrying with SPAN extension...
2023-04-13 18:37:36.713 ERROR Z-WAVE-SERVER: Cannot send this message because it would exceed the maximum payload length! (ZW0215)
ZWaveError: Cannot send this message because it would exceed the maximum payload length! (ZW0215)
at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4182:23)
at Driver.sendCommandInternal (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4375:28)
at Driver.sendSupervisedCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4420:27)
at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4477:30)
at ColorSwitchCCAPI.set (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ColorSwitchCC.ts:232:38)
at Proxy.ColorSwitchCCAPI.<computed> (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ColorSwitchCC.ts:461:17)
at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:961:29)
at NodeMessageHandler.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:23:38)
at Object.node (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:41:96)
at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:106:99)
18:37:58.378 SERIAL » 0x012500133c1e9f03ca0012a048d49e862832cd38d9b48b4dbe47c7a4292d8036f (39 bytes)
510c3582515a9
18:37:58.384 DRIVER » [Node 060] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 21
└─[Security2CCMessageEncapsulation]
│ sequence number: 202
└─[MultiChannelCCCommandEncapsulation]
│ source: 0
│ destination: 1
└─[SupervisionCCGet]
│ session id: 60
│ request updates: true
└─[ColorSwitchCCSet]
Red: 255
Green: 255
Blue: 0
duration: default
18:37:58.391 SERIAL « [ACK] (0x06)
18:37:58.398 SERIAL « 0x0104011301e8 (6 bytes)
18:37:58.402 SERIAL » [ACK] (0x06)
18:37:58.406 DRIVER « [RES] [SendData]
was sent: true
18:37:58.466 SERIAL « 0x011800131500000701cd7f7f7f7f0101030c0000000201000026 (26 bytes)
18:37:58.470 SERIAL » [ACK] (0x06)
18:37:58.474 DRIVER « [REQ] [SendData]
callback id: 21
transmit status: OK, took 70 ms
repeater node IDs: 12
routing attempts: 1
protocol & route speed: Z-Wave, 40 kbit/s
ACK RSSI: -51 dBm
ACK RSSI on repeaters: N/A
ACK channel no.: 1
TX channel no.: 1
18:37:58.553 SERIAL « 0x011c0004003c149f0202016cbffbaca33b43be4ea7a862075e512bcd007d (30 bytes)
18:37:58.556 SERIAL » [ACK] (0x06)
18:37:58.559 DRIVER « [Node 060] [REQ] [ApplicationCommand]
└─[Security2CCNonceReport]
sequence number: 2
SOS: true
MOS: false
receiver entropy: 0x6cbffbaca33b43be4ea7a862075e512b
18:37:58.564 CNTRLR [Node 060] failed to decode the message, retrying with SPAN extension...
2023-04-13 18:37:58.576 ERROR Z-WAVE-SERVER: Cannot send this message because it would exceed the maximum payload length! (ZW0215)
ZWaveError: Cannot send this message because it would exceed the maximum payload length! (ZW0215)
at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4182:23)
at Driver.sendCommandInternal (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4375:28)
at Driver.sendSupervisedCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4420:27)
at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4477:30)
at ColorSwitchCCAPI.set (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ColorSwitchCC.ts:232:38)
at Proxy.ColorSwitchCCAPI.<computed> (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ColorSwitchCC.ts:461:17)
at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:961:29)
at NodeMessageHandler.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:23:38)
at Object.node (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:41:96)
at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:106:99)
18:38:03.586 SERIAL » 0x0103003bc7 (5 bytes)
18:38:03.588 DRIVER » [REQ] [GetBackgroundRSSI]
18:38:03.591 SERIAL « [ACK] (0x06)
18:38:03.594 SERIAL « 0x0105013bb3abd8 (7 bytes)
18:38:03.596 SERIAL » [ACK] (0x06)
18:38:03.599 DRIVER « [RES] [GetBackgroundRSSI]
channel 0: -77 dBm
channel 1: -85 dBm
18:38:21.694 SERIAL » 0x011f00133c189f03cc00826e50950dbadf9a3232070565ed925a74630e862516b (33 bytes)
2
18:38:21.697 DRIVER » [Node 060] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 22
└─[Security2CCMessageEncapsulation]
│ sequence number: 204
└─[MultiChannelCCCommandEncapsulation]
│ source: 0
│ destination: 1
└─[SupervisionCCGet]
│ session id: 61
│ request updates: true
└─[MultilevelSwitchCCSet]
target value: 255
duration: default
18:38:21.701 SERIAL « [ACK] (0x06)
18:38:21.706 SERIAL « 0x0104011301e8 (6 bytes)
18:38:21.708 SERIAL » [ACK] (0x06)
18:38:21.714 DRIVER « [RES] [SendData]
was sent: true
18:38:21.776 SERIAL « 0x011800131600000701ca7f7f7f7f0101030c0000000201000022 (26 bytes)
18:38:21.777 SERIAL » [ACK] (0x06)
18:38:21.779 DRIVER « [REQ] [SendData]
callback id: 22
transmit status: OK, took 70 ms
repeater node IDs: 12
routing attempts: 1
protocol & route speed: Z-Wave, 40 kbit/s
ACK RSSI: -54 dBm
ACK RSSI on repeaters: N/A
ACK channel no.: 1
TX channel no.: 1
18:38:21.863 SERIAL « 0x011c0004003c149f0203014ae04d3de2b1b9687a5aeb3c4c28ae42cd00ba (30 bytes)
18:38:21.865 SERIAL » [ACK] (0x06)
18:38:21.867 DRIVER « [Node 060] [REQ] [ApplicationCommand]
└─[Security2CCNonceReport]
sequence number: 3
SOS: true
MOS: false
receiver entropy: 0x4ae04d3de2b1b9687a5aeb3c4c28ae42
18:38:21.872 CNTRLR [Node 060] failed to decode the message, retrying with SPAN extension...
18:38:21.886 SERIAL » 0x013100133c2a9f03cd01124142398828dad6240034497807c79aa973aa9e72e9c (51 bytes)
620d1db8d22fef67497982aed89f7732517d9
18:38:21.888 DRIVER » [Node 060] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 23
└─[Security2CCMessageEncapsulation]
│ sequence number: 205
│ extensions:
│ · type: SPAN
│ sender EI: 0x42398828dad6240034497807c79aa973
└─[MultiChannelCCCommandEncapsulation]
│ source: 0
│ destination: 1
└─[SupervisionCCGet]
│ session id: 61
│ request updates: true
└─[MultilevelSwitchCCSet]
target value: 255
duration: default
18:38:21.892 SERIAL « [ACK] (0x06)
18:38:21.899 SERIAL « 0x0104011301e8 (6 bytes)
18:38:21.901 SERIAL » [ACK] (0x06)
18:38:21.903 DRIVER « [RES] [SendData]
was sent: true
18:38:22.037 SERIAL « 0x011800131700000e01cd7f7f7f7f0101030c000000020100002d (26 bytes)
18:38:22.039 SERIAL » [ACK] (0x06)
18:38:22.044 DRIVER « [REQ] [SendData]
callback id: 23
transmit status: OK, took 140 ms
repeater node IDs: 12
routing attempts: 1
protocol & route speed: Z-Wave, 40 kbit/s
ACK RSSI: -51 dBm
ACK RSSI on repeaters: N/A
ACK channel no.: 1
TX channel no.: 1
18:38:22.124 SERIAL « 0x011d0004003c159f03040087a09b8db2ab822c956ebd747cf99f49e4cd0099 (31 bytes)
18:38:22.128 SERIAL » [ACK] (0x06)
18:38:22.130 DRIVER « [Node 060] [REQ] [ApplicationCommand]
└─[Security2CCMessageEncapsulation]
│ sequence number: 4
└─[MultiChannelCCCommandEncapsulation]
│ source: 1
│ destination: 0
└─[SupervisionCCReport]
session id: 61
more updates follow: false
status: Success
duration: 0s
18:38:27.170 SERIAL » 0x011900133c129f03ce007b5b9d84cfed6b8765ced2cf65f1251861 (27 bytes)
18:38:27.173 DRIVER » [Node 060] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 24
└─[Security2CCMessageEncapsulation]
│ sequence number: 206
└─[MultiChannelCCCommandEncapsulation]
│ source: 0
│ destination: 1
└─[MultilevelSwitchCCGet]
18:38:27.179 SERIAL « [ACK] (0x06)
18:38:27.185 SERIAL « 0x0104011301e8 (6 bytes)
18:38:27.188 SERIAL » [ACK] (0x06)
18:38:27.192 DRIVER « [RES] [SendData]
was sent: true
18:38:27.259 SERIAL « 0x011800131800000801cd7f7f7f7f0101030c0000000201000024 (26 bytes)
18:38:27.261 SERIAL » [ACK] (0x06)
18:38:27.263 DRIVER « [REQ] [SendData]
callback id: 24
transmit status: OK, took 80 ms
repeater node IDs: 12
routing attempts: 1
protocol & route speed: Z-Wave, 40 kbit/s
ACK RSSI: -51 dBm
ACK RSSI on repeaters: N/A
ACK channel no.: 1
TX channel no.: 1
18:38:27.344 SERIAL « 0x011d0004003c159f030500e83003635d56a639afab92f72f0a446f97cd004f (31 bytes)
18:38:27.348 SERIAL » [ACK] (0x06)
18:38:27.351 CNTRLR [Node 060] [~] [Multilevel Switch] targetValue: 255 => 99 [Endpoint 1]
18:38:27.354 CNTRLR [Node 060] [~] [Multilevel Switch] duration: {"value":0,"unit":"s [Endpoint 1]
econds"} => {"value":0,"unit":"seconds"}
18:38:27.356 CNTRLR [Node 060] [~] [Multilevel Switch] currentValue: 0 => 99 [Endpoint 1]
18:38:27.359 DRIVER « [Node 060] [REQ] [ApplicationCommand]
└─[Security2CCMessageEncapsulation]
│ sequence number: 5
└─[MultiChannelCCCommandEncapsulation]
│ source: 1
│ destination: 0
└─[MultilevelSwitchCCReport]
current value: 99
target value: 99
duration: 0s
18:38:28.321 SERIAL « 0x010e0004000d06310504220026d0001a (16 bytes)
18:38:28.324 SERIAL » [ACK] (0x06)
18:38:28.327 CNTRLR [Node 013] [Multilevel Sensor] Power: metadata updated [Endpoint 0]
18:38:28.330 CNTRLR [Node 013] [~] [Multilevel Sensor] Power: 3.9 => 3.8 [Endpoint 0]
18:38:28.332 DRIVER « [Node 013] [REQ] [ApplicationCommand]
└─[MultilevelSensorCCReport]
type: Power
scale: Watt
value: 3.8
18:38:33.595 SERIAL » 0x0103003bc7 (5 bytes)
18:38:33.598 DRIVER » [REQ] [GetBackgroundRSSI]
18:38:33.604 SERIAL « [ACK] (0x06)
18:38:33.609 SERIAL « 0x0105013bb1b1c0 (7 bytes)
18:38:33.613 SERIAL » [ACK] (0x06)
18:38:33.618 DRIVER « [RES] [GetBackgroundRSSI]
channel 0: -79 dBm
channel 1: -79 dBm
18:38:33.700 SERIAL » 0x012500133c1e9f03cf009f34fc83649cab4d75166cb2797b3865a7c0dcc90c5b7 (39 bytes)
82c1a95251952
18:38:33.704 DRIVER » [Node 060] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 25
└─[Security2CCMessageEncapsulation]
│ sequence number: 207
└─[MultiChannelCCCommandEncapsulation]
│ source: 0
│ destination: 1
└─[SupervisionCCGet]
[debuglog.txt](https://github.com/zwave-js/node-zwave-js/files/11225541/debuglog.txt)

│ session id: 62
│ request updates: true
└─[ColorSwitchCCSet]
Red: 255
Green: 0
Blue: 0
duration: default
18:38:33.709 SERIAL « [ACK] (0x06)
18:38:33.714 SERIAL « 0x0104011301e8 (6 bytes)
18:38:33.716 SERIAL » [ACK] (0x06)
18:38:33.719 DRIVER « [RES] [SendData]
was sent: true
18:38:33.796 SERIAL « 0x011800131900000801cd7f7f7f7f0101030c0000000201000025 (26 bytes)
18:38:33.798 SERIAL » [ACK] (0x06)
18:38:33.801 DRIVER « [REQ] [SendData]
callback id: 25
transmit status: OK, took 80 ms
repeater node IDs: 12
routing attempts: 1
protocol & route speed: Z-Wave, 40 kbit/s
ACK RSSI: -51 dBm
ACK RSSI on repeaters: N/A
ACK channel no.: 1
TX channel no.: 1
18:38:33.884 SERIAL « 0x011d0004003c159f03060046e7b2053eecfbf91fe914c57442c65821cd00f0 (31 bytes)
18:38:33.888 SERIAL » [ACK] (0x06)
18:38:33.892 DRIVER « [Node 060] [REQ] [ApplicationCommand]
└─[Security2CCMessageEncapsulation]
│ sequence number: 6
└─[MultiChannelCCCommandEncapsulation]
│ source: 1
│ destination: 0
└─[SupervisionCCReport]
session id: 62
more updates follow: false
status: Success
duration: 0s
18:38:33.901 CNTRLR [Node 060] [~] [Color Switch] currentColor[2]: 255 => 255 [Endpoint 1]
18:38:33.903 CNTRLR [Node 060] [~] [Color Switch] currentColor[3]: 0 => 0 [Endpoint 1]
18:38:33.906 CNTRLR [Node 060] [~] [Color Switch] currentColor[4]: 0 => 0 [Endpoint 1]
18:38:33.908 CNTRLR [Node 060] [~] [Color Switch] currentColor: {"red":255,"green":0, [Endpoint 1]
"blue":0} => {"red":255,"green":0,"blue":0}
18:38:33.911 CNTRLR [Node 060] [~] [Color Switch] targetColor: {"red":255,"green":0," [Endpoint 1]
blue":0} => {"red":255,"green":0,"blue":0}
18:38:33.916 CNTRLR [Node 060] [~] [Color Switch] hexColor: "ff0000" => "ff0000" [Endpoint 1]
18:38:33.939 SERIAL » 0x011f00133c189f03d000ff0ebaa68b75ad2eb808c0263ad0a6a1aac31014251ae (33 bytes)
2
18:38:33.945 DRIVER » [Node 060] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 26
└─[Security2CCMessageEncapsulation]
│ sequence number: 208
└─[MultiChannelCCCommandEncapsulation]
│ source: 0
│ destination: 1
└─[SupervisionCCGet]
│ session id: 63
│ request updates: true
└─[MultilevelSwitchCCSet]
target value: 25
duration: default
18:38:33.949 SERIAL « [ACK] (0x06)
18:38:33.954 SERIAL « 0x0104011301e8 (6 bytes)
18:38:33.956 SERIAL » [ACK] (0x06)
18:38:33.958 DRIVER « [RES] [SendData]
was sent: true
18:38:34.049 SERIAL « 0x011800131a00000901cd7f7f7f7f0101030c0000000201000027 (26 bytes)
18:38:34.050 SERIAL » [ACK] (0x06)
18:38:34.053 DRIVER « [REQ] [SendData]
callback id: 26
transmit status: OK, took 90 ms
repeater node IDs: 12
routing attempts: 1
protocol & route speed: Z-Wave, 40 kbit/s
ACK RSSI: -51 dBm
ACK RSSI on repeaters: N/A
ACK channel no.: 1
TX channel no.: 1
18:38:34.134 SERIAL « 0x011d0004003c159f030700019ebe62ce1eb9769c72e323ccdba05e19cd001b (31 bytes)
18:38:34.139 SERIAL » [ACK] (0x06)
18:38:34.141 DRIVER « [Node 060] [REQ] [ApplicationCommand]
└─[Security2CCMessageEncapsulation]
│ sequence number: 7
└─[MultiChannelCCCommandEncapsulation]
│ source: 1
│ destination: 0
└─[SupervisionCCReport]
session id: 63
more updates follow: false
status: Success
duration: 0s
18:38:34.148 CNTRLR [Node 060] [~] [Multilevel Switch] currentValue: 99 => 25 [Endpoint 1]
```

**Comment by AlCalzone** [comment]
Can you tell me exactly what the scene is trying to set for which entity? I might also need a diagnostic dump for that device.

**Comment by thecobra666** [comment]
As requested by Alcalzone: This is the yaml of the scenes I'm trying to call.

```
- id: '1656341612753'
  name: Badkamer Knop ROOD
  entities:
    light.badkamer_lichten:
      supported_color_modes:
      - hs
      friendly_name: Badkamer LED lampje
      supported_features: 32
      color_mode: hs
      brightness: 64
      hs_color:
      - 0
      - 100
      rgb_color:
      - 255
      - 0
      - 0
      xy_color:
      - 0.701
      - 0.299
      state: 'on'
  icon: mdi:bathtub
  metadata:
    light.badkamer_lichten:
      entity_only: true
- id: '1656341659630'
  name: Badkamer LED geel
  entities:
    light.badkamer_lichten:
      supported_color_modes:
      - hs
      friendly_name: Badkamer LED lampje
      supported_features: 32
      color_mode: hs
      brightness: 255
      hs_color:
      - 60
      - 100
      rgb_color:
      - 255
      - 255
      - 0
      xy_color:
      - 0.444
      - 0.517
      state: 'on'
  icon: mdi:bathtub
  metadata:
    light.badkamer_lichten:
      entity_only: true
```

**Comment by AlCalzone** [comment]
Is there any way to set the brightness before the color?

**Comment by thecobra666** [comment]
> Is there any way to set the brightness before the color?

Not in a scene. It's all in one.

**Comment by AlCalzone** [comment]
I thought you maybe have an influence on the ordering of commands. It looks like it first sends the color change (the larger command), but that requires a re-sync of the encryption state, which puts it above the threshold. Then it sends the brightness change which is small enough to go through.

**Comment by thecobra666** [comment]
> I thought you maybe have an influence on the ordering of commands. It looks like it first sends the color change (the larger command), but that requires a re-sync of the encryption state, which puts it above the threshold. Then it sends the brightness change which is small enough to go through.

The point of a scene is to set the light(s) to a specific state and then call it. I did notice the same behavior when creating an automation to do the same action (which makes sense cause it creates the same problem) 

The annoying thing is that the light then refuses to react on any command. I must turn it off and on again (in HA or zwavejsui) to make it respond to commands again.

**Comment by kpine** [comment]
What was the automation that you tried to use? Did you try splitting up the brightness and color settings into separate actions? E.g. turn_on with brightness only, turn_on with color only.

**Comment by thecobra666** [comment]
> What was the automation that you tried to use? Did you try splitting up the brightness and color settings into separate actions? E.g. turn_on with brightness only, turn_on with color only.

I did, but even that did not always work.

**Comment by kpine** [comment]
With the same error message, or other reason?

You might want to upload the driver logs for that automation, for Al to compare.

**Comment by AlCalzone** [comment]
Ok, looks like the command that should be transmitted is 48 bytes long. With explorer frames, the maximum is 46, without (but with routing) 48.
So we should be able to detect this and disable explorer frames when the payload is too long. Any longer won't work though, as routing would have to be disabled next.

**Comment by AlCalzone** [comment]
@thecobra666 Can you please send me a re-interview log of that device?
It should support transport service, so I'm a bit confused why that's not being used here to get around the issue.

**Comment by thecobra666** [comment]
> @thecobra666 Can you please send me a re-interview log of that device? It should support transport service, so I'm a bit confused why that's not being used here to get around the issue.

[zwavejs_2023-04-14.log](https://github.com/zwave-js/node-zwave-js/files/11232532/zwavejs_2023-04-14.log)

As requested

**Comment by AlCalzone** [comment]
Ok now I'm confused. It does support Transport Service CC v2, so the error you're seeing shouldn't be possible.
Just for my sanity, can you try activating the scene again now and log that?

**Comment by thecobra666** [comment]
> Ok now I'm confused. It does support Transport Service CC v2, so the error you're seeing shouldn't be possible. Just for my sanity, can you try activating the scene again now and log that?

[log.txt](https://github.com/zwave-js/node-zwave-js/files/11240334/log.txt)

That works just fine now and it's indeed using the transport service. I did had to reïnterview it again cause in HA it didn't identify as being able to change colors, yet in zwavejs-ui I did had the option to change it.

**Comment by AlCalzone** [comment]
Ok that looks better. You probably had some communication troubles during the initial interview. Will close this then - the PR should make this better in case transport service is actually not supported.

**Comment by thecobra666** [comment]
> Ok that looks better. You probably had some communication troubles during the initial interview. Will close this then - the PR should make this better in case transport service is actually not supported.

Is there a way for the end user to see when the interview was not finished correctly?

**Comment by AlCalzone** [comment]
Not currently, but I plan to expose interview failures in a more fine-grained way:
https://github.com/zwave-js/node-zwave-js/issues/985
