### ISSUE TITLE
Error when receiving message from unknown node

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#5710]
```
ZWaveError: Node 5 was not found! (ZW0209)
  at /snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/zwave-js/src/lib/controller/Controller.ts:380:10
  at Map.<anonymous> (/snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/@zwave-js/shared/src/ThrowingMap.ts:17:5)
  at Driver.getHighestSecurityClass (/snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/zwave-js/src/lib/driver/Driver.ts:792:38)
  at new Security2CCMessageEncapsulation (/snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/@zwave-js/cc/src/cc/Security2CC.ts:837:15)
  at new CommandClass (/snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/@zwave-js/cc/src/lib/CommandClass.ts:137:13)
  at new Security2CC (/snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/@zwave-js/cc/src/cc/Security2CC.ts:461:8)
  at Function.from (/snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/@zwave-js/cc/src/lib/CommandClass.ts:370:16)
  at new ApplicationCommandRequest (/snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/zwave-js/src/lib/serialapi/application/ApplicationCommandRequest.ts:88:32)
  at Function.from (/snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/@zwave-js/serial/src/message/Message.ts:255:15)
  at Driver.serialport_onData (/snap/zwave-js-ui/157/lib/zwave-js-ui/node_modules/zwave-js/src/lib/driver/Driver.ts:2777:18)
```

**Comment by AshtonKem** [comment]
Seeing this after having some issues with a zooz door sensor. Now I can't include this sensor to the network.
