### ISSUE TITLE
Zwave controller stops responding

### ISSUE THREAD

**Issue by ocalvo** [AlCalzone/node-zwave-js#5947]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

YES, BUT a Z-Wave JS UI developer has told me to come here

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

What do you observe?

What did you expect to happen?
Network to automatically reset controller. Today a maual restart of the addon is required.

  1. After 24-48 hours, the controller stops responding.

### Device information

Manufacturer: Aeotec 
Model name: USB 7
Node ID in your network: TBD

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwave-js-ui` branch:

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

```
2023-06-26 15:10:01.303 INFO Z-WAVE: [Node 057] Value updated: 113-0-alarmLevel 0 => 0
2023-06-26 15:10:01.310 INFO Z-WAVE: [Node 057] Value updated: 113-0-Home Security-Motion sensor status 8 => 0
2023-06-26 15:10:01.436 INFO Z-WAVE: [Node 057] Metadata updated: 48-0-Motion
2023-06-26 15:10:01.440 INFO Z-WAVE: [Node 057] Value updated: 48-0-Motion true => false
2023-06-26 15:10:05.763 INFO Z-WAVE: [Node 126] Value updated: 113-0-alarmType 0 => 0
2023-06-26 15:10:05.769 INFO Z-WAVE: [Node 126] Value updated: 113-0-alarmLevel 0 => 0
2023-06-26 15:10:05.775 INFO Z-WAVE: [Node 126] Value updated: 113-0-Home Security-Motion sensor status 8 => 0
2023-06-26 15:10:05.832 INFO Z-WAVE: [Node 126] Metadata updated: 48-0-Motion
2023-06-26 15:10:05.837 INFO Z-WAVE: [Node 126] Value updated: 48-0-Motion true => false
2023-06-26 15:10:12.136 INFO Z-WAVE: [Node 133] Value updated: 113-0-alarmType 0 => 0
2023-06-26 15:10:12.141 INFO Z-WAVE: [Node 133] Value updated: 113-0-alarmLevel 0 => 0
2023-06-26 15:10:12.151 INFO Z-WAVE: [Node 133] Value updated: 113-0-Home Security-Motion sensor status 8 => 0
2023-06-26 15:10:12.322 INFO Z-WAVE: [Node 133] Metadata updated: 48-0-Motion
2023-06-26 15:10:12.325 INFO Z-WAVE: [Node 133] Value updated: 48-0-Motion true => false
2023-06-26 15:10:14.272 INFO APP: GET /health/zwave 200 2.706 ms - 2140
2023-06-26 15:10:14.629 INFO Z-WAVE: [Node 133] Value updated: 113-0-alarmType 0 => 0
2023-06-26 15:10:14.633 INFO Z-WAVE: [Node 133] Value updated: 113-0-alarmLevel 0 => 0
2023-06-26 15:10:14.642 INFO Z-WAVE: [Node 133] Value updated: 113-0-Home Security-Motion sensor status 0 => 8
2023-06-26 15:10:14.818 INFO Z-WAVE: [Node 133] Metadata updated: 48-0-Motion
2023-06-26 15:10:14.833 INFO Z-WAVE: [Node 133] Value updated: 48-0-Motion false => true
2023-06-26 15:10:20.440 INFO Z-WAVE: [Node 112] Metadata updated: 50-0-value-66561
2023-06-26 15:10:20.443 INFO Z-WAVE: [Node 112] Value updated: 50-0-value-66561 116.96 => 96.58
2023-06-26T21:10:27.491Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:10:28.596Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26T21:10:30.704Z CNTRLR   [Node 198] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
2023-06-26T21:10:32.212Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:10:33.317Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26T21:10:35.424Z CNTRLR   [Node 198] did not respond after 2/3 attempts. Scheduling next try in 500 ms.
2023-06-26T21:10:36.936Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:10:38.039Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26 15:10:40.151 ERROR Z-WAVE-SERVER: Timeout while waiting for an ACK from the controller (ZW0200)
ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4322:23)
    at Driver.sendCommandInternal (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4519:28)
    at Driver.sendCommand (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4630:15)
    at Proxy.get (/opt/node_modules/@zwave-js/cc/src/cc/ManufacturerSpecificCC.ts:106:24)
    at ZWaveController.getAvailableFirmwareUpdates (/opt/node_modules/zwave-js/src/lib/controller/Controller.ts:5803:5)
    at Function.handle (/opt/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:205:54)
    at Object.controller (/opt/node_modules/@zwave-js/server/dist/lib/server.js:39:103)
    at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:106:99)
    at WebSocket.<anonymous> (/opt/node_modules/@zwave-js/server/dist/lib/server.js:50:45)
    at WebSocket.emit (node:events:513:28)
2023-06-26 15:10:44.649 INFO APP: GET /health/zwave 200 3.542 ms - 2140
2023-06-26T21:10:46.164Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:10:47.268Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26 15:11:14.791 INFO APP: GET /health/zwave 200 2.150 ms - 2140
2023-06-26T21:11:16.165Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:11:17.269Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26 15:11:44.954 INFO APP: GET /health/zwave 200 3.170 ms - 2140
2023-06-26T21:11:46.167Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:11:47.274Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26T21:11:55.576Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:11:56.683Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26T21:11:58.788Z CNTRLR   [Node 027] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
2023-06-26T21:12:00.302Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:12:01.406Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26T21:12:03.516Z CNTRLR   [Node 027] did not respond after 2/3 attempts. Scheduling next try in 500 ms.
2023-06-26T21:12:05.025Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:12:06.134Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26 15:12:08.250 ERROR Z-WAVE-SERVER: Timeout while waiting for an ACK from the controller (ZW0200)
ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4322:23)
    at Driver.sendCommandInternal (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4519:28)
    at Driver.sendSupervisedCommand (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4564:27)
    at Driver.sendCommand (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4612:30)
    at Proxy.set (/opt/node_modules/@zwave-js/cc/src/cc/MultilevelSwitchCC.ts:248:24)
    at Proxy.<anonymous> (/opt/node_modules/@zwave-js/cc/src/cc/MultilevelSwitchCC.ts:324:17)
    at ZWaveNode.setValue (/opt/node_modules/zwave-js/src/lib/node/Node.ts:996:39)
    at NodeMessageHandler.handle (/opt/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:23:38)
    at Object.node (/opt/node_modules/@zwave-js/server/dist/lib/server.js:41:96)
    at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:106:99)
2023-06-26T21:12:09.271Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-26T21:12:10.375Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-26T21:12:12.482Z CNTRLR   [Node 012] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
2023-06-26T21:12:13.249Z CNTRLR » [Node 019] Multilevel Sensor CC values may be stale, refreshing...
2023-06-26T21:12:13.251Z CNTRLR » [Node 019] querying Dew point sensor reading...
2023-06-26T21:12:13.257Z CNTRLR   [Node 019] No scale preference for sensor type 11, using the first supported s
                                  cale 0
2023-06-26T21:12:13.993Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
```

**Comment by AlCalzone** [comment]
Duplicate of #2723

That said, I've actually never seen 700 series sticks suddenly go unresponsive, so this might be a hardware or OS issue.
I'm not sure how you are running Z-Wave JS, is a VM with USB passthrough involved somehow?

**Comment by jriguera** [comment]
I am facing a similar issue (not sure if it is the same). The controller is a aeotec ZST10-700 (FW: v7.19.2 / SDK: v7.19.2) running on Raspberry Pi with docker and using the latest version of Zwave JS UI (zwave-js-ui: 8.19.0.487524b ; zwave-js: 11.0.0). I am still investigating a bit the behavior. 

This is some output:

```
2023-06-28 18:08:41.997 ERROR Z-WAVE-SERVER: Timeout while waiting for an ACK from the controller (ZW0200)
ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4366:23)
    at Driver.sendCommandInternal (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4563:28)
    at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4674:15)
    at Proxy.set (/usr/src/app/node_modules/@zwave-js/cc/src/cc/MultilevelSwitchCC.ts:251:24)
    at Proxy.<anonymous> (/usr/src/app/node_modules/@zwave-js/cc/src/cc/MultilevelSwitchCC.ts:327:17)
    at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:1019:39)
    at NodeMessageHandler.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:20:43)
    at Object.node (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:41:96)
    at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:106:99)
    at WebSocket.<anonymous> (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:50:45)
2023-06-28 18:10:00.371 ERROR Z-WAVE-SERVER: Failed to send the message after 3 attempts (ZW0202)
ZWaveError: Failed to send the message after 3 attempts (ZW0202)
    at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4366:23)
    at Driver.sendCommandInternal (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4563:28)
    at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4674:15)
    at Proxy.get (/usr/src/app/node_modules/@zwave-js/cc/src/cc/VersionCC.ts:243:40)
    at ZWaveController.getAvailableFirmwareUpdates (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:5861:61)
    at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:201:30)
    at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:106:62)
2023-06-28 18:14:51.383 ERROR Z-WAVE-SERVER: Cannot check for firmware updates for node 18: Failed to query fingerprint from the node! (ZW0260)
ZWaveError: Cannot check for firmware updates for node 18: Failed to query fingerprint from the node! (ZW0260)
    at ZWaveController.getAvailableFirmwareUpdates (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:5854:10)
    at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:201:30)
    at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:106:62)
2023-06-28 18:20:01.140 ERROR Z-WAVE-SERVER: Failed to send the message after 3 attempts (ZW0202)
ZWaveError: Failed to send the message after 3 attempts (ZW0202)
    at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4366:23)
    at Driver.sendCommandInternal (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4563:28)
    at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4674:15)
    at Proxy.get (/usr/src/app/node_modules/@zwave-js/cc/src/cc/VersionCC.ts:243:40)
    at ZWaveController.getAvailableFirmwareUpdates (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:5861:61)
    at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:201:30)
    at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:106:62)
2023-06-28 18:32:01.144 ERROR Z-WAVE-SERVER: Timeout while waiting for an ACK from the controller (ZW0200)
ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4366:23)
    at Driver.sendCommandInternal (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4563:28)
    at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4674:15)
    at Proxy.get (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ManufacturerSpecificCC.ts:109:24)
    at ZWaveController.getAvailableFirmwareUpdates (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:5851:5)
    at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:201:30)
    at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:106:62)
```


There are some log lines of the driver:

```

2023-06-28T16:25:46.883Z SERIAL « 0x010f00a80001100631050122010b00a4f6                                (17 bytes)
2023-06-28T16:25:46.889Z SERIAL » [ACK]                                                                   (0x06)
2023-06-28T16:25:46.897Z CNTRLR   [Node 016] [Multilevel Sensor] Air temperature: metadata updated  [Endpoint 0]
2023-06-28T16:25:46.899Z CNTRLR   [Node 016] [~] [Multilevel Sensor] Air temperature: 26.5 => 26.7  [Endpoint 0]
2023-06-28T16:25:46.900Z DRIVER « [Node 016] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -92 dBm
                                  └─[MultilevelSensorCCReport]
                                      type:  Air temperature
                                      scale: Celsius
                                      value: 26.7
2023-06-28T16:25:47.074Z SERIAL » 0x0103003bc7                                                         (5 bytes)
2023-06-28T16:25:47.076Z DRIVER » [REQ] [GetBackgroundRSSI]
2023-06-28T16:25:48.082Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-06-28T16:25:48.184Z SERIAL » 0x0103003bc7                                                         (5 bytes)
2023-06-28T16:25:48.185Z DRIVER » [REQ] [GetBackgroundRSSI]
2023-06-28T16:25:48.194Z SERIAL « [CAN]                                                                   (0x18)
2023-06-28T16:25:48.198Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-06-28T16:25:48.425Z SERIAL « 0x011300a80001100a600d010031050122010b00a48a                        (21 bytes)
2023-06-28T16:25:48.430Z SERIAL » [ACK]                                                                   (0x06)
2023-06-28T16:25:48.434Z CNTRLR   [Node 016] [Multilevel Sensor] Air temperature: metadata updated  [Endpoint 1]
2023-06-28T16:25:48.438Z CNTRLR   [Node 016] [~] [Multilevel Sensor] Air temperature: 26.5 => 26.7  [Endpoint 1]
2023-06-28T16:25:48.442Z DRIVER « [Node 016] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -92 dBm
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      1
                                    │ destination: 0
                                    └─[MultilevelSensorCCReport]
                                        type:  Air temperature
                                        scale: Celsius
                                        value: 26.7
2023-06-28T16:25:49.299Z SERIAL » 0x0103003bc7                                                         (5 bytes)
2023-06-28T16:25:49.300Z DRIVER » [REQ] [GetBackgroundRSSI]
2023-06-28T16:25:49.309Z SERIAL « [ACK]                                                                   (0x06)
2023-06-28T16:25:49.319Z SERIAL « 0x0107013b9a90907f27                                                 (9 bytes)
2023-06-28T16:25:49.321Z SERIAL » [ACK]                                                                   (0x06)
2023-06-28T16:25:49.325Z DRIVER « [RES] [GetBackgroundRSSI]
                                    channel 0: -102 dBm
                                    channel 1: -112 dBm
                                    channel 2: -112 dBm
2023-06-28T16:25:56.666Z SERIAL » 0x011400a9010608600d00012601ffff25000000002605                      (22 bytes)
2023-06-28T16:25:56.669Z DRIVER » [Node 006] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ callback id:      38
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 1
                                    └─[MultilevelSwitchCCSet]
                                        target value: 255
                                        duration:     default
2023-06-28T16:25:56.707Z SERIAL « [ACK]                                                                   (0x06)
2023-06-28T16:25:56.711Z SERIAL « 0x010401a90152                                                       (6 bytes)
2023-06-28T16:25:56.713Z SERIAL » [ACK]                                                                   (0x06)
2023-06-28T16:25:56.717Z DRIVER « [RES] [SendDataBridge]
                                    was sent: true
2023-06-28T16:25:58.254Z SERIAL « 0x011d00a92600000100b57f7f7f7f00000300000000030100007f7f7f7f7fa7    (31 bytes)
2023-06-28T16:25:58.257Z SERIAL » [ACK]                                                                   (0x06)
2023-06-28T16:25:58.261Z DRIVER « [REQ] [SendDataBridge]
                                    callback id:            38
                                    transmit status:        OK, took 10 ms
                                    routing attempts:       1
                                    protocol & route speed: Z-Wave, 100 kbit/s
                                    ACK RSSI:               -75 dBm
                                    ACK channel no.:        0
                                    TX channel no.:         0
2023-06-28T16:25:59.799Z SERIAL « 0x011400a80001060b5601600d010126030c447600b5db                      (22 bytes)
2023-06-28T16:25:59.807Z SERIAL » [ACK]                                                                   (0x06)
2023-06-28T16:25:59.811Z CNTRLR   [Node 006] [~] [Multilevel Switch] currentValue: 0 => 12          [Endpoint 1]
2023-06-28T16:25:59.814Z CNTRLR   [Node 006] Scheduled poll canceled because expected value was received
2023-06-28T16:25:59.818Z DRIVER « [Node 006] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -75 dBm
                                  └─[CRC16CCCommandEncapsulation]
                                    └─[MultiChannelCCCommandEncapsulation]
                                      │ source:      1
                                      │ destination: 1
                                      └─[MultilevelSwitchCCReport]
                                          current value: 12

``` 

What I also see is a increase in CPU usage, in normal conditions the nodejs process does not consume CPU and sending commands via HA (power off/on lights) is instantaneous, but when the CPU goes a bit crazy (> 130% and load above 1.4), then is when those `Failed to execute controller command after 1/3 attempts.` appear.  I have rebuild the zwave network without security and the behavior seems similar.  The zwave network was build without HA (not even deployed), all actions were done from the Zwave JS UI interface and the first day (sorry I have no data) after adding all devices it was fine (normal cpu usage, but also no actions performed from the controller). A day later, same devices and same configuration those problems appear.
