### ISSUE TITLE
SendDataMulticast with status `Fail` exposed as `NoAck`

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#7198]
### Discussed in https://github.com/zwave-js/node-zwave-js/discussions/7194

<div type='discussions-op-text'>

<sup>Originally posted by **@Botched1** September 26, 2024</sup>
I'm using a ZST39 running 7.22.1 and see multicast commands fail somewhat regularly. If I repeatedly send multicast commands I can get it to give the error maybe 3 out of 10 times or so... 

[...]

What I see in the logs when it fails:

```
2024-09-25 20:30:38.430 ERROR Z-WAVE-SERVER: The node did not acknowledge the command (ZW0204)
ZWaveError: The node did not acknowledge the command (ZW0204)
    at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:5816:23)
    at Driver.sendCommandInternal (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:6014:28)
    at Driver.sendCommand (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:6124:29)
    at BinarySwitchCCAPI.set (/opt/node_modules/@zwave-js/cc/src/cc/BinarySwitchCC.ts:142:24)
    at BinarySwitchCCAPI.<anonymous> (/opt/node_modules/@zwave-js/cc/src/cc/BinarySwitchCC.ts:164:16)
    at VirtualNode.setValue (/opt/node_modules/zwave-js/src/lib/node/VirtualNode.ts:172:39)
    at MulticastGroupMessageHandler.handle (/opt/node_modules/@zwave-js/server/dist/lib/multicast_group/message_handler.js:19:50)
    at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:139:100)
    at WebSocket.<anonymous> (/opt/node_modules/@zwave-js/server/dist/lib/server.js:60:45)
    at WebSocket.emit (node:events:517:28)
```
[...]

</div>

Investigation of the driver logs indicates that this is a transmit status of `Fail`, not `NoAck`, so it should be exposed as such.

**Comment by luantaraschi** [comment]
I'd like to take this one, unless someone is already on it.

Reading the driver: for SendData, `queueSerialAPICommand` returns the transmit report instead of throwing when the callback is NOK, so `serialAPICommandErrorToZWaveError` never runs for these. The throw that does run is the `!prevResult.isOK()` one at the end of the send loop, and it is fixed to the NoAck message and `Controller_CallbackNOK` no matter what `transmitStatus` says. That lines up with the log in the discussion.

My plan is to derive both from the status, the way `StateMachineShared.ts` already does, and cover it with an integration test using the mock controller.
